### ISSUE TITLE
Speedup of powers

### ISSUE THREAD

**Issue by aedolfi** [Zitzeronion/Swalbe.jl#27]
Implementing the disjoing pressure as 

```
function power_2(arg::Float64)
	return arg * arg 
end

function power_3(arg::Float64)
	return arg * arg * arg
end

function power_9(arg::Float64)
	temp = power_3(arg)
	return power_3(temp)
end

function fast_disj_32(arg::Float64)
    return power_3(arg)-power_2(arg)
end

function fast_disj_93(arg::Float64)
    temp = power_3(arg)
    return power_3(temp)-temp
end
```

leads to a speedup of 4-5 times compared with 

```
power_broad(arg,3)-power_broad(arg,2)
```
or
```
power_broad(arg,9)-power_broad(arg,3)
```
Thus I would implement them. 
Questions to discuss are 
- howis it implemented as comfortable as possible for the user?
- Does `if n==9 && m==3` cost unnecesarry time or is the compiler clever enough to factor it out
- Do we also want to implement things like $`n=6,m=3`$ as used by Uwe Thieles group

![image](https://user-images.githubusercontent.com/80793262/222458103-4a86a328-79ee-4947-933f-776bae0b6ac2.png)

**Comment by aedolfi** [comment]
Actually `power_9` is not needed, we only need prime numbers, every non-prime is a waste of time

**Comment by aedolfi** [comment]
Doing an ifelse is not a perfomance issue, the compiler while be clever enough to compile it out

![image](https://user-images.githubusercontent.com/80793262/222460284-d7524701-814c-49ff-8b2d-26144b462d19.png)

**Comment by Zitzeronion** [comment]
> Doing an ifelse is not a perfomance issue, the compiler while be clever enough to compile it out

Always a good feeling when something you guessed is actually true 😀.
Thanks for the work, I will implement it shortly.

**Comment by aedolfi** [comment]
I just ran one of my simulations, that due to the second field should have more overhead, and if I am not overseeing something it gave me an incredible speedup of factor 8

**Comment by Zitzeronion** [comment]
Should be according to your suggestions @aedolfi. Only have the two powers which are used in papers, thanks again for pointing out a way to increase performance 🚀
